const Action={
    AUTH_SUCCESS:'AUTH_SUCCESS',
    LOGOUT:'LOGOUT',
    AUTH_INITIATE:'AUTH_INITIATE',
    SIGNIN_ERRORS:'SIGNIN_ERRORS',
    SIGNUP_ERROR:"SIGNUP_ERROR",
    ADD_LIST_BLOG:'ADD_LIST_BLOG',
    INITIATE_BLOGLIST:'INITIATE_BLOGLIST',
    BLOG_CREATED:"BLOG_CREATED",
    POPUP:'POPUP',
    SHOW_PROFILE:'SHOW_PROFILE',
    DELETE_BLOG:'DELETE_BLOG',
    UPDATE_BLOG:'UPDATE_BLOG',
   

}

export default Action